#!/usr/bin/env python3
"""Generates src/html/src/entities_generated.inc from the WHATWG HTML named
character reference table.

Source: https://html.spec.whatwg.org/entities.json (committed at
tools/html/entities.json).  This is the authoritative named character
reference table from the WHATWG HTML Standard (§13.2.5.73).

Regenerate with:

    python3 tools/gen_html_entities.py

The generated file is checked in; do not edit it by hand.
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "tools", "html", "entities.json")
OUT = os.path.join(ROOT, "src", "html", "src", "entities_generated.inc")


def main() -> int:
    with open(SRC, "r", encoding="utf-8") as f:
        table = json.load(f)

    # The spec table keys look like "&AElig;" (semicolon form, always valid)
    # and "&amp" (legacy no-semicolon form).  Build the semicolon table plus
    # the legacy set of names that may omit the trailing semicolon.
    named = []  # (name, codepoints list)
    legacy = set()
    for key, value in table.items():
        if not key.startswith("&"):
            continue
        if key.endswith(";"):
            named.append((key[1:-1], value["codepoints"]))
        else:
            legacy.add(key[1:])

    named.sort(key=lambda entry: entry[0])

    lines = []
    lines.append("// Generated by tools/gen_html_entities.py from")
    lines.append("// tools/html/entities.json (WHATWG HTML Standard §13.2.5.73).")
    lines.append("// DO NOT EDIT — regenerate with: python3 tools/gen_html_entities.py")
    lines.append("")
    lines.append(f"// {len(named)} named character references (sorted by name).")
    lines.append("constexpr NamedEntity kNamedEntities[] = {")
    for name, cps in named:
        count = min(len(cps), 2)
        padded = (cps + [0, 0])[:2]
        lines.append(
            f'    {{"{name}", {{{hex(padded[0])}, {hex(padded[1])}}}, {count}}},'
        )
    lines.append("};")
    lines.append("")
    lines.append(f"// {len(legacy)} legacy names that may omit the trailing semicolon.")
    lines.append("constexpr std::string_view kLegacyNoSemicolon[] = {")
    for name in sorted(legacy):
        lines.append(f'    "{name}",')
    lines.append("};")
    lines.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"wrote {OUT}: {len(named)} entities, {len(legacy)} legacy no-semicolon names")
    return 0


if __name__ == "__main__":
    sys.exit(main())
